### ISSUE TITLE
Errors out if the post/page content is empty

### ISSUE THREAD

**Issue by amardeep-sidhu** [ashishb/wp2hugo#55]
I faced an issue while exporting my wordpress blog. There was one page which was empty. It was a contact page and had some widget (from a 3rd party contact plugin) there but no other text. The utility errored out while exporting that page. Simple fix was to edit the wordpress post and insert some text there, export the XML again and it worked fine. Maybe in such cases, it can generate an empty .md file.

**Comment by ashishb** [comment]
@amardeep-sidhu 

Thanks.
Yeah, this was intentional to catch the scenarios where the page might contain elements that `wp2hugo` failed to parse.
It is a bit hard to distinguish between the page is empty vs my parsing logic being incorrect.
I will try to add a CLI parameter to convert this into a warning.
